ALTER TABLE user_vehicles ADD COLUMN IF NOT EXISTS brand VARCHAR(50);
ALTER TABLE user_vehicles ADD COLUMN IF NOT EXISTS model VARCHAR(50);
ALTER TABLE user_vehicles ADD COLUMN IF NOT EXISTS year INTEGER;
ALTER TABLE user_vehicles ADD COLUMN IF NOT EXISTS city_consumption DECIMAL(5,2);
ALTER TABLE user_vehicles ADD COLUMN IF NOT EXISTS highway_consumption DECIMAL(5,2);